// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwoH9masEqaGoOqF6tHvHiCfoF_I4hNbk',
    appId: '1:976781468666:web:261e907d7993e1a96ffa43',
    messagingSenderId: '976781468666',
    projectId: 'chat-app-24309',
    authDomain: 'chat-app-24309.firebaseapp.com',
    storageBucket: 'chat-app-24309.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTa58fuVOzSaFNLJRfAk8L24mIJ2r5qk4',
    appId: '1:976781468666:android:24ec8df4ad3980996ffa43',
    messagingSenderId: '976781468666',
    projectId: 'chat-app-24309',
    storageBucket: 'chat-app-24309.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAO6Qy1sUfK05MzzHc75H3_t5l62Ck13N0',
    appId: '1:976781468666:ios:e47aafccdab1b7836ffa43',
    messagingSenderId: '976781468666',
    projectId: 'chat-app-24309',
    storageBucket: 'chat-app-24309.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAO6Qy1sUfK05MzzHc75H3_t5l62Ck13N0',
    appId: '1:976781468666:ios:e47aafccdab1b7836ffa43',
    messagingSenderId: '976781468666',
    projectId: 'chat-app-24309',
    storageBucket: 'chat-app-24309.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwoH9masEqaGoOqF6tHvHiCfoF_I4hNbk',
    appId: '1:976781468666:web:f575879a13b6aff66ffa43',
    messagingSenderId: '976781468666',
    projectId: 'chat-app-24309',
    authDomain: 'chat-app-24309.firebaseapp.com',
    storageBucket: 'chat-app-24309.appspot.com',
  );
}
